Add files via upload
Mindshift-Analytics/roicalculator pull request #31
Opened 2024-12-05 16:44 UTC by ReddyYesh

Improved bar chart visualization in server.R

2024-12-06 02:55 UTC, sanjmeh commented
Will check today. Thanks.

2024-12-06 11:03 UTC, sanjmeh requested changes
unfortunately the code has diverged. So you need to do a `git rebase origin/main`. 
in case it doesn't work, please reform from the main and send a new PR.

2024-12-09 05:03 UTC, bkowshik requested changes
Thank you for this PR @ReddyYesh 

I see that there is a duplicate copy in `server.R`, the same code is copied twice, could be by mistake. Can you please clean up this PR, removing the duplicate code. Please post here once it's done and this Pull Request is ready for our review.

2024-12-09 05:03 UTC, bkowshik commented on server.R
> +# Ensure the latest version of gt is installed
@ReddyYesh This is the start of the duplicate copy.

2024-12-10 03:47 UTC, closed without merging